notepad-plus-plus/nppPluginList

appveyor.yml, pl.schema, validator.py
- reduce to relevant builds
- separate check for json for 64 and 32 bit list
- added changes from https://github.com/dail8859/nppPluginList/tree/jsonvalidator for enhanced json check
=> Appveyor build enhancement

appveyor.yml, pl.schema, validator.py
Adds quite a few checks to the validator
=> Validator updates

src/pl.x64.json, src/pl.x86.json
Also remove `/releases` from homepage since it seems to be more correct looking at other plugins.
=> Update DSpellCheck to 1.4.8.

src/pl.x64.json, src/pl.x86.json
Updated for Customize Toolbar 4.2.
=> Customize Toolbar 4.2

src/pl.x64.json, src/pl.x86.json
This is the current version of AnalysePlugin 1.11.37 modified zips have been uploaded to my repo
=> Adding AnalysePlugin to new PluginsAdmin

src/pl.x64.json, src/pl.x86.json
Tested locally, requires wingup 5.1 as it was suffering from the 0KB bug
=> Added Code Alignment to the Plugin List

src/pl.x64.json, src/pl.x86.json
Updated the Explorer plugin for x86
Added the Explorer plugin for x64
=> Update Explorer plugin

src/pl.x86.json
=> update SQLinForm to 5.3.25

src/pl.x64.json
I did the SHA256 calculation with Npp Tools again. Hope it is fine now
=> update SQLinForm tp 5.3.25

src/pl.x64.json, src/pl.x86.json
Update NppMarkdownPanel to Version 0.4.0
=> Update NppMarkdownPanel to Version 0.4.0

src/pl.x64.json, src/pl.x86.json
=> NppTextViz

src/pl.x64.json
LanguageHelp, MenuIcons, OpenSelection, RunMe, TakeNotes, TopMost
=> Added several plugins

src/pl.x64.json, src/pl.x86.json
=> add NppMenuSearch plugin

pl.schema, src/pl.x64.json, src/pl.x86.json, validator.py
Add plugin release date: 
- json key: release-date
- type: string
- pattern: \\d\\d\\d\\d-\\d\\d-\\d\\d
Type date seems not to be supported yet until json schema draft 7.
=> add plugin release date

src/pl.x64.json, src/pl.x86.json
Adapted to Scintilla v4.1.4 API
=> Update CustomLineNumbers to v1.1.7

src/pl.x64.json, src/pl.x86.json
Update AutoCodepage to v1.2.4
Re-Release of CustomLineNumbers v1.1.7
=> Update AutoCodepage, Re-Release CustomLineNumbers

README.md
Add Build status badge and release badge
=> add build status badge and release badge

src/pl.x64.json, src/pl.x86.json
Add IncredibleJunior plugins:
- Tortoise SVN
- Solution Hub
- Solution Hub UI
- Solution Tools
- Open File In Solution
=> add IncredibleJunior plugins

src/pl.x64.json, src/pl.x86.json
added new version of NppMarkdownPanel 0.5.0
=> added new version of NppMarkdownPanel 0.5.0

src/pl.x64.json, src/pl.x86.json
I deleted the release data tag and do my PR again.
=> add qkNppReverseLines v1.0.0.0

src/pl.x64.json, src/pl.x86.json
Created Linefilter3 plugin, to be added to x64 & x86 plugin list
=> Added Linefilter3 to the plugin list (x64 & x86)

src/pl.x64.json, src/pl.x86.json
@chcg can you help me there [jn npp plugin Owner](https://github.com/sieukrem/jn-npp-plugin/pull/80#issuecomment-531342133) could not understand my pull request
=> bug fixed creating new line

src/pl.x64.json, src/pl.x86.json
[Merge files in one review](https://youtu.be/WVxDQnOj3oo)
=> New "Merge files in one" plugin

src/pl.x64.json, src/pl.x86.json
Added BigFiles plugin in both platform x86 and x64.
=> Add BigFiles plugin x86 and x64

src/pl.x64.json, src/pl.x86.json
It now includes a 64-bit version of the plugin as well
=> Release of IndentByFold v0.7.2

src/pl.x64.json, src/pl.x86.json
Added "Automation Scripts" (NppScripts) plugin that has been ported to x64 platform
=> Added "Automation Scripts" (NppScripts) plugin

src/pl.x86.json
=> Upgrade SQLinForm to 5.3.35

src/pl.x64.json
Upgrade SQLinForm 64 to 5.3.35
=> Upgrade SQLinForm 64 to 5.3.35

src/pl.x86.json
Submitting request to include the x86 version of GotoLineCol plugin.
=> Updating pl.x86.json to include GotoLineCol plugin

src/pl.x64.json
Submitting request to include the x64 version of GotoLineCol plugin.
=> Updating pl.x64.json to include GotoLineCol plugin

src/pl.x64.json, src/pl.x86.json
NppSnippets v1.5.1 has been released
=> NppSnippets v1.5.1

src/pl.x64.json, src/pl.x86.json
- Update LuaScript to v0.10
- Update BetterMultiSelection to v1.4
- Update SurroundSelection to v1.4.1
=> Various plugin updates

src/pl.x64.json, src/pl.x86.json
New plugin version fix a crash with using "view" button on xmltools options + improve centering on annoted line
=> Upgrade XMLTools to version 3.0.1.0

src/pl.x64.json, src/pl.x86.json
In Version 1.12 are new features like:
- grouping patterns
- identifying what pattern did match in selected line
- saving results in rtf document including background colors
- modifying columns in pattern list
- number of hits per pattern
- enabling word wrap in results
- custom colors persistent over sessions
Synced with NPP code 7.8.2
See more details and fixed bugs in changes.txt
=> Update AnalysePlugin to v1.12-R43

src/pl.x64.json, src/pl.x86.json
In Version 1.12 are new features like:
- grouping patterns
- identifying what pattern did match in selected line
- saving results in rtf document including background colors
- modifying columns in pattern list
- number of hits per pattern
- enabling word wrap in results
- custom colors persistent over sessions
Synced with NPP code 7.8.2
See more details and fixed bugs in changes.txt
=> Update AnalysePlugin to version 1.12-R44

src/pl.x64.json, src/pl.x86.json
Update Comment Wrap version and move all my plugins to new host.
=> Update Comment Wrap version and move all my plugins to new host.

src/pl.x64.json, src/pl.x86.json
=> Upgrade to XMLTools 3.0.3.4

src/pl.x86.json
Hello,
it for publish CADdaTools-plugin x86.
regards Mario
=> Insert CADdyTools-plugin

src/pl.x64.json
Hello,
i wish publish my plugin with pluginmanager.
regards mario
=> Insert Plugin CADdyTools

src/pl.x64.json, src/pl.x86.json
Additional fix for bug (https://sourceforge.net/p/analyseplugin/bugs/76/) crash at shuttdown of NPP
In Version 1.12 are new features like:
- grouping patterns
- identifying what pattern did match in selected line
- saving results in rtf document including background colors
- modifying columns in pattern list
- number of hits per pattern
- enabling word wrap in results
- custom colors persistent over sessions
Synced with NPP code 7.8.2
See more details and fixed bugs in changes.txt
=> Update AnalysePlugin to version 1.12-R47

src/pl.x64.json, src/pl.x86.json
fix issue https://github.com/gurikbal/Remove_dup_lines/issues/5
=> update Remove_dup_lines plugin

src/pl.x64.json
... sorry, the previous sha-256 are from wrong file ... 8-()
=> update CADdyTools Plugin

.gitignore, validator.py
Adding a generator of plugin list md files for both architectures.
=> Topic 158 pl md

validator.py
In previous version restriction to max 100 chars was not always working.
This makes the table even more bad readable when width is restricted.
This version should do the job bit better.
=> Changing pl md generation to create summary with consistent length

src/pl.x86.json
So this is my plugin, i hope i did everything required for this initial version.
=> Added DarkTheme Plugin

src/pl.x64.json
I still need to fix a problem with the 32-bit version, so I am skipping it.
=> Update BigFiles x64 to v0.1.2.0

src/pl.x64.json, src/pl.x86.json
New plugin SelectToClipboard
Update NppTextViz to v0.4.2
=> Add SelectToClipboard

src/pl.x64.json, src/pl.x86.json
=> Upgrade JSTool to 1.2006.0.

src/pl.x64.json, src/pl.x86.json
Hi, Please accept update for JSONViewer plugin.
=> add jsonviewer 1.4 release

src/pl.x64.json, src/pl.x86.json
Today I released NppSnippets v1.6.0
=> Release of NppSnippets v1.6.0

src/pl.x64.json, src/pl.x86.json
As suggested in editorconfig/editorconfig-notepad-plus-plus#37
=> Update description EditorConfig

src/pl.x86.json
same with x64 ;-)
many thanks for your works
=> Update CADdyTools from 1.0.1.5 to 1.1.3.7

src/pl.x64.json, src/pl.x86.json
This PR updates wakatime plugin to 4.2.0. Should I change the id of each package also? If so how to do it?
=> update wakatime to 4.2.0

src/pl.x64.json, src/pl.x86.json
This PR updates WakaTime checksum for both platforms.
=> Update WakaTime to 4.2.1

src/pl.x64.json, src/pl.x86.json
Hoping to add this plugin for RestApiToText. I have tested for both 32-bit and 64-bit and it appears to be working.
=> Adding RestApiToText Plugin

src/pl.x64.json, src/pl.x86.json
- removed no longer available  NppCCompletionPlugin
=> - added nppexec 0.6.1

src/pl.x64.json, src/pl.x86.json
Initial version of ERP Helper.
A set of utilities for developing ERP integrations, includes XSL transformation and Workday API SOAP calls.
=> ERP Helper v1.0.0

README.md
Thank you for Notepad++.  I cleaned up this file to make it more usable and easier to read.
=> Many improvements

src/pl.x64.json, src/pl.x86.json
=> Update list with NppSaveAsAdmin 1.0.211

src/pl.x64.json
My 2 plugins support x64 and update it
=> Add 2 plugins( LocationNavigate , NewFileBrowser ) to x64 list

src/pl.x64.json, src/pl.x86.json
=> Rest api to test version 1.2.1.0

src/pl.x64.json, src/pl.x86.json
Release output are generated with GitHub action: https://github.com/blu3mania/npp-papyrus/blob/main/.github/workflows/release.yml
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/674478214
Workflow: https://github.com/blu3mania/npp-papyrus/blob/main/.github/workflows/codeql-analysis.yml
=> Add Papyrus Script Lexer plugin v0.1.0.8 to both 64bit and 32bit plugin lists

src/resource.h
=> Fix version

src/resource.h
Reverts notepad-plus-plus/nppPluginList#273
=> Revert "Fix version"

src/pl.x64.json, src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/699839552
=> Update Papyrus Script Lexer plugin to v0.2.0.16 for both 64bit and 32bit

src/pl.x64.json, src/pl.x86.json
FWDataViz 1.0.2.0 Update adds Automatic File Type Detection (ADFT) feature for fixed-width data files.
=> FWDataViz 1.0.2.0 Update (x86 & x64)

src/pl.x86.json
Fix crash due to a buffer overrun
=> Update TakeNotes to v1.22

src/pl.x64.json, src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/1018759092
=> Update Papyrus Script Lexer plugin to v0.2.3.23 for both x64 and x86

src/pl.x86.json
Fix a bug in the create new note function
=> Update TakeNotes to v1.2.3

src/pl.x64.json, src/pl.x86.json
Better error messages
Dark mode icons
=> Update CsvQuery to v1.2.8

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
I am sorry for the frequent PRs from my repo. The FWDataViz plugin had quite a few features and some fixes during the last couple of months. I was holding off on this PR. But then I received a request from one of my plugin users to not wait. Thank you!
=> v2.1.2.1 Release

src/pl.x64.json
Fixed the file list generation and some file conversion that did not work with German language
=> Fix some file conversion

src/pl.x86.json
Did not work properly with some languages such as German
=> Fix some file conversion issues

src/pl.x64.json, src/pl.x86.json
=> CSV Lint plug-in update

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.2
=> CSV Lint plug-in update v0.4.2

src/pl.x64.json, src/pl.x86.json
Adds the nppRandomStringGenerator to the PluginList x86 and x64
=> Adds nppRandomStringGenerator

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.3
=> CSV Lint plug-in update v0.4.3

src/pl.x64.json, src/pl.x86.json
https://github.com/wakatime/notepadpp-wakatime/blob/master/HISTORY.rst
=> Upgrade WakaTime plugin to v4.2.3

src/pl.x64.json, src/pl.x86.json
=> Turned .rar to .zip

src/pl.x64.json, src/pl.x86.json
updated VinsWorldcom plugins:  ColumnTools, QuickText
=> updated VinsWorldcom ColumnTools, QuickText

src/pl.x64.json, src/pl.x86.json
=> VinsWorldcom updates for 8.2.2

src/pl.x64.json, src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/1885547309
=> Update Papyrus Script Lexer plugin to v0.3.0.24 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
=> Update JSTool to 1.2202.0.

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.2.1/NEWS.textile
=> Update HTMLTag to 1.2.1

src/pl.x64.json, src/pl.x86.json
CSV Lint new version and shorter single-line descriptions for both CSV Lint and RandomValuesNppPlugin
=> CSV Lint new version and shorter descriptions

src/pl.x64.json, src/pl.x86.json
=> CS-Script update v1.7.29

src/pl.x64.json, src/pl.x86.json
=> GitSCM 1.4.7.1

src/pl.x64.json, src/pl.x86.json
I hope I got the compatibility versions format correct.
=> Update kered13 plugins.

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.2.2/NEWS.textile
=> Update HTMLTag to 1.2.2

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.2.3/NEWS.textile
=> Update HTMLTag to 1.2.3

src/pl.x64.json, src/pl.x86.json
Hello,
Added my recent plugin here on the list: NWScript Tools Lexer and Compiler.
Thanks.
=> Add Plugin - NWScript Tools Lexer and Compiler v1.0.2

src/pl.x64.json, src/pl.x86.json
Updates CsvQuery so it works with Npp 8.3 and up
=> Update CsvQuery to 1.2.9

src/pl.x64.json, src/pl.x86.json
Fix dark mode for 8.4.1 - changed NPPM message struct.
=> NWScript Tools v1.0.3.1950

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
With immediate change of dark mode tones based on NPPM_GETDARKMODECOLORS & NPPN_DARKMODECHANGED APIs in Notepad++ 8.4.1
=> FWDataViz v2.5.0.0 and GotoLineCol v2.3.0.0 Releases

src/pl.x64.json, src/pl.x86.json
=> Update JSTool to 1.2205.0.

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.5.2
=> CSV Lint plug-in update v0.4.5.2

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.3.4/NEWS.textile
=> HTMLTag v1.3.4

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.3.5/NEWS.textile
=> HTMLTag v1.3.5

src/pl.x64.json, src/pl.x86.json
Added the version parameters for the nppRandomStringGenerator plugin
=> Updated versions parameters for nppRandomStringGenerator

src/pl.x64.json, src/pl.x86.json
See https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v3.6.0
=> JsonTools v3.6.0

src/pl.x64.json, src/pl.x86.json
=> update GitSCM to 1.4.8.1

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6
=> CSV Lint plug-in update v0.4.6

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.1
=> CSV Lint plug-in update v0.4.6.1

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
@chcg a critical regression found in v20.2.0 is fixed. Please consider this for upcoming release.
Sorry for inconvenience and thanks!
=> JsonViewer release v2.0.3.0

src/pl.x64.json, src/pl.x86.json
Updating to RestApiToText Version 1.3.1.1
=> Change to use RestApiToText Version 1.3.1.1

src/pl.x64.json, src/pl.x86.json
See https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/CHANGELOG.md#400---2022-10-24
=> Update JsonTools to v4.0.0

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.2
=> CSV Lint plug-in update v0.4.6.2

src/pl.x64.json, src/pl.x86.json
I think I'm too late for current Notepad++ update now though :sob:
=> update Code::Stats to v1.1.1

src/pl.x64.json, src/pl.x86.json
Second commit "Revert changes in data of CS-Script plugin" reverts a JSON reformat in data of CS-Script plugin caused by my automated deploy scripts.
=> Update AutoCodepage to v1.2.5

src/pl.x64.json, src/pl.x86.json
- Update AutoEolFormat to v1.0.3
- Update CustomLineNumbers to v1.1.8
- Update NppUISpy to v1.1
I have no idea why my previous commits regarding my AutoCodepage plugin are repeated. If this is a problem, please advise me how to fix that. I'm a newbie in using Git.
=> Update plugins AutoEolFormat, CustomLineNumbers and NppUISpy

src/pl.x64.json, src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/3416298035
=> Update Papyrus Script Lexer plugin to v0.5.0.28 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
Npp-Highlighter draw indicator on scroll bar when:
- line contents changed
- double clicked and smart highlighted words
- text highlighted by Style token
For more details, please go to [https://github.com/michaelxzhang/Npp-Highlighter](https://github.com/michaelxzhang/Npp-Highlighter)
=> Request to add Npp-Highlighter plugin

src/pl.x64.json, src/pl.x86.json
See https://github.com/molsonkiko/JsonToolsNppPlugin/releases specifically https://github.com/molsonkiko/JsonToolsNppPlugin/releases/v4.4
=> Update JsonTools to v4.4

src/pl.x64.json, src/pl.x86.json
Update [GitSCM](https://github.com/vinsworldcom/nppGitSCM) to 1.4.8.2
=> GitSCM 1.4.8.2

src/pl.x64.json, src/pl.x86.json
https://github.com/wakatime/notepadpp-wakatime/blob/master/HISTORY.rst#500-2002-12-04
=> Upgrade WakaTime plugin to v5.0.1

src/pl.x64.json, src/pl.x86.json
Hi,
I had a longer break from publishing this plug-in, but now I've at least finally ported it to 64 bit.
It's tested via plugin admin as described.
Thank you!
=> Request to add "SourceCookifier" to the 64 bit plug-ins list

src/pl.x64.json, src/pl.x86.json
added Markdown Panel (NppMarkdownPanel) release 0.7.0
=> Markdown Panel (NppMarkdownPanel) release 0.7.0

src/pl.x64.json, src/pl.x86.json
=> Updated Npp Highlighter plug-in to version 1.0.0.1

src/pl.x64.json, src/pl.x86.json
Ref:
https://github.com/notepad-plus-plus/nppPluginList/pull/545#issuecomment-1354383280
=> Remove SQLinForm for fixing CI

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.3.6/NEWS.textile
=> HTMLTag v1.3.6

src/pl.x64.json, src/pl.x86.json
Also:
* update source repository URL, description
* introduce a 64-bit version
See https://bitbucket.org/rdipardo/dbgp/src/v0.14/CHANGELOG.txt
=> Update DBGp to 0.14

src/pl.x64.json
=> Added SQLinFormNpp64 again

src/pl.x86.json
=> added SQLinForm again

src/pl.x64.json, src/pl.x86.json
Markdown Panel (NppMarkdownPanel) release 0.7.1 added
=> Markdown Panel (NppMarkdownPanel) release 0.7.1 added

src/pl.x64.json, src/pl.x86.json
https://github.com/wakatime/notepadpp-wakatime/blob/master/HISTORY.rst#510-2023-01-07
=> Upgrade WakaTime plugin to v5.1.0

src/pl.x64.json
=> Update MenuIcons to v2.02

src/pl.x64.json, src/pl.x86.json
Updated NppMarkdownPanel to Version 0.7.2
=> Updated NppMarkdownPanel to Version 0.7.2

src/pl.x64.json, src/pl.x86.json
Update NppMarkdownPanel to Version 0.7.3 (Bugfix Release)
=> Update NppMarkdownPanel to Version 0.7.3 (Bugfix Release)

src/pl.x86.json
OpenAI (aka. ChatGPT) plugin for Notepad++
=> New NppOpenAI v0.1 plugin

src/pl.x86.json
Updated SHA-256 id for NppOpenAI.zip: it contains now the optimized version of the plugin DLL
=> Updated NppOpenAI id

src/pl.x64.json
Fix issue https://github.com/francostellari/NppPlugins/issues/40
=> TakeNotes v1.25

src/pl.x64.json, src/pl.x86.json
- Release of AutoCodepage plugin v1.2.6
- Release of AutoEolFormat plugin v1.0.4
=> Update plugins AutoCodepage and AutoEolFormat 

src/pl.x64.json, src/pl.x86.json
This update 
* improves presentation of indicator panel on high resolution monitors 
* fixes wrong behavior by addressing cascaded menu items
=> Update jN up to 2.2.185.9

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.3.7/NEWS.textile
=> HTMLTag v1.3.7

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/dbgp/src/v0.14.1/CHANGELOG.txt
=> Update DBGp to 0.14.1

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.4
=> CSV Lint plug-in update v0.4.6.4

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.5
=> CSV Lint plug-in update v0.4.6.5

src/pl.x64.json, src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/5350461019
=> Update Papyrus Script Lexer plugin to v1.0.1.32 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
=> Update Papyrus Script Lexer plugin to v1.1.0.33 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
Updates for NppOpenAI plugin:
• Better UX (loader window, multithread support, better error handling)
• Configuration/Settings updates (custom API URL, no token limit etc.)
• Fixed JSON errors bug: better memory handling
• Code optimizations
=> NppOpenAI updates

src/pl.x64.json, src/pl.x86.json
Release notes: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.6.4
Documentation:  https://github.com/young-developer/nppNavigateTo/tree/master/documentation
=> Update NavigateTo v.2.6.4.0

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
**Core functions:**
- Multiple Replacements: Perform many replacements at once.
- Find Feature: Utilize list or individual search for elements.
- Toggle List Entries: Switch entries for replacement, search, or highlight on/off.
- CSV Storage: Manage search/replace strings via CSV lists.
- Bash Script Export: Script replacements via bash script exports.
- Unique Highlighting Colors: Use 20+ colors to highlight "find words".
- Compatibility: Fully compatible with Notepad++ search parameters.
=> MultiReplace 1.0.0.1 (initial release)

validator.py
| Revision | Message | Modified Files |
|----------------|---------|----------------|
| 55e5231 | Added a fallback to the 'x86' architecture. | validator.py |
| c2cbbdb | Refactored architecture selection and file handling. | validator.py |
| 274804e | Optimized imports. | validator.py |
| a20385f | Improved error messages and comments. | validator.py |
| 3dd5135 | Refactored the code to adhere to the PEP 8 formatting guidelines. | validator.py |
=> Validator improvements and optimizations

src/pl.x64.json, src/pl.x86.json
Naturally, I found a bug right after the previous update was released.
=> Update Comment Wrap.

src/pl.x64.json
=> Add Comment Toggler to the x64 list

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.4.1/NEWS.textile
=> HTMLTag v1.4.1

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
Update JSTool to 1.2308.0 and add ARM64 support.
=> Update JSTool to 1.2308.0 and add ARM64 support.

src/pl.x64.json, src/pl.x86.json
Updates nppRandomStringGenerator to v1.7.0
=> Update nppRandomStringGenerator v1.7.0

src/pl.x64.json, src/pl.x86.json
=> Update Papyrus Script Lexer plugin to v1.2.0.330 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
Hi Admin,
I have updated both pl.x64.json and pl.x86.json to include an update for RegexTrainer from 1.0.0 to 1.1.0
Thanks,
Ahmoy Law
=> Update for RegexTrainer ver 1.1.0

src/pl.x64.json, src/pl.x86.json
Hi admin,
Please merge the json for both x64 and x86 on my new RegexTrainer ver 1.2.0 (to support huge files and few UI enhancements).
The descriptions for the ver 1.2.0 is available at this link 
https://github.com/ahmoylaw/RegexTrainer-Descriptions
And sorry since i don't know on how to use Release on github.
Thanks,
Ahmoy Law
=> Modified for RegexTrainer ver 1.2.0

src/pl.x64.json, src/pl.x86.json
=> Update Papyrus Script Lexer plugin to v1.2.1.340 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
Update EnhanceAnyLexer plugin to version 1.4.0
=> Release new EnhanceAnyLexer version

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
=> Release JSTool 1.2311.0.

src/pl.x64.json, src/pl.x86.json
Add a new plugin, Columns++, version 1.0, to the x86 and x64 plugins lists.
=> Add Columns++ version 1.0 to x86 and x64 plugins lists.

src/pl.x64.json, src/pl.x86.json
This updates nppRandomStringGenerator to v1.9.0
=> Update nppRandomStringGenerator to v1.9.0

src/pl.x64.json, src/pl.x86.json
=> Update Papyrus Script Lexer plugin to v1.2.2.354 for both x64 and x86

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.6
=> CSV Lint plug-in update v0.4.6.6

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/dbgp/src/v0.14.2.1/CHANGELOG.txt
=> Update DBGp to 0.14.2.1

src/pl.x64.json, src/pl.x86.json
Random Values plug-in update v0.3
=> Random Values plug-in update v0.3

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
=> Release JSTool 1.2312.0.

src/pl.x64.json, src/pl.x86.json
=> Update GitSCM to v1.4.9.1

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **"Replace first match only" Checkbox**: Specifically designed for 'Replace All' actions within list operations in combination with the same find values.
- **Help Button for 'Use Variables'**: Direct access to in-depth documentation for the 'Use Variables' feature.
- **Enhancements in 'Use Variables' with init({})**: Introduces variable initialization, facilitating the passing of values from previous Replace Operations to the next ones for more complex replacements.
=> updated MultiReplace to v 2.2.0.9

src/pl.x64.json, src/pl.x86.json
=> added NppGZipFileViewer 3.0.1

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Sorting Lines in CSV by Columns**: Ascend or descend, combining columns in any prioritized order.
- **Deleting Multiple Columns**: Simultaneously remove various columns, cleaning up any obsolete delimiters.
- **Clipboard Column Copying**: Instantly copy columns, complete with original delimiters, into the clipboard.
=> MultiReplace v2.3.0.10

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.4.3/NEWS.textile
=> HTMLTag v1.4.3

src/pl.x64.json, src/pl.x86.json
https://github.com/rdipardo/nppFSIPlugin/blob/v0.2.2.0/Changelog.txt
=> F# Interactive v0.2.2.0

src/pl.x64.json, src/pl.x86.json
- Update to CSScriptNpp v2.0.4.0
=> Update to CSScriptNpp v2.0.4.0

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Multilingual Support**: The plugin now allows for configuring the UI to accommodate multiple languages.
- **Toolbar Access and Icon**: The plugin can now be accessed directly through the toolbar, featuring a new icon for quick access.
- **Bug Fix**: Addressed an error with the "Replace All" function when utilizing the "Selection" scope feature.
=> update MultiReplace to 2.4.0.11

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.4.4/NEWS.textile
=> HTMLTag v1.4.4

src/pl.x64.json, src/pl.x86.json
workaround for https://github.com/vladk1973/npp.connections/issues/5
=> Nppconnection v1.1

src/pl.x64.json, src/pl.x86.json
(fixed an issue that doesn't work on recent npp versions)
Before this fix i changed fold flags to hide folding lines, now change fold line transparency.
Please review and pull this request. thanks!
=> FoldingLineHider v1.1

src/pl.x64.json, src/pl.x86.json
Updated JSON files to reflect latest version of BookmarksDook plugin.
=> Update JSON - current version of BookmarksDook.

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Enhanced Statistics Columns**: Added additional columns to display statistics for found and replaced values, providing more detailed insights.
- **Improved Sorting Functionality**: Enhanced the ability to revert to the original sorting order of the CSV file, even after rows are modified, deleted, or added.
- **New Context Menu**: Introduced a new context menu for the list, offering a comprehensive overview of all available functions.
- **Direct List Editing Features**: Users can now perform copy, paste, and edit operations directly within the list.
- **Dark Mode Support for Help Page**: The help page for the 'Use Variables' option now supports Dark Mode.
=> updated MultiReplace to v3.0.0.12

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
**Fixed issue where:**
- quotes were removed when pasting.
- entries were not inserted at the correct position in the list.
- special characters were removed from CAPs.
=> updated MultiReplace to v3.0.1.13

src/pl.x64.json, src/pl.x86.json
Added support for programming languages Hollywood, Go and Raku.
=> Update AutoCodepage to v1.2.7

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- Updated the edit field in the list to automatically remove line breaks when pasting, enabling support for complex "Use Variables" statements.
- Added correct escaping of special characters in "Use Variables" when used with regex.
- Optimized nil checks in conditional statements.
- escaped special characters in languages.ini
=> updated MultiReplace to v3.0.2.14

src/pl.x64.json, src/pl.x86.json
Update Columns++ to version 1.1.2.
=> Update Columns++ to version 1.1.2

src/pl.x64.json
Blitz Search is my standalone file searching project.
=> Add Blitz Search To the list

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- Added `DEBUG` option for 'Use Variables' to inspect global variables during replacements, with a message box for each hit.
- Fixed paste functionality to correctly insert/replace text in the edit field without overwriting existing content.
- Several fixes in `languages.ini`.
- Corrected file type filter options in the open file dialog windows to display the filtering endings correctly.
=> updated MultiReplace to v3.0.3.15

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.7
=> CSV Lint plug-in update v0.4.6.7

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- added arm64 bin
- updated libplist to the latest available in vcpkg 2023-06-15#1
=> Update NppBplistPlugin to v3.0.0.0

src/pl.x64.json, src/pl.x86.json
This update fixes randomness not being as random as it should
=> Updates nppRandomStringGenerator to v1.9.2

src/pl.x64.json
Hi Team, I would like to add a new plugin to Notepad++ plugin list. This plugin is created for the ASCII library data of Siemens NX CAM.  It includes two functionalities in the menu list:
- Format Database: Align the data of each CLASS with its corresponding attribute in format line.
- Show Class: Create a dialog box, extract the name of each type and show the number of items in type, and implement a jump to the corresponding row after clicking on the class name.
=> Introduce a new plugin NX ASCII Database Helper

src/pl.x64.json, src/pl.x86.json
No word yet from @vor0nwe about what he thinks, but I don't think he would mind (<https://fossil.2of4.net/npp_preview/wiki/Deprecation>).
Fixes #791
=> Update Preview HTML and change repository

src/pl.x64.json, src/pl.x86.json
See [the release page](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.1) for all the changes in this release.
=> Up JsonTools to v8.1

src/pl.x64.json, src/pl.x86.json
https://github.com/rdipardo/npp_preview/blob/v1.3.3.1/ReleaseNotes.txt
=> Preview HTML v1.3.3.1

src/pl.x64.json
Fix an issue of menu and correct the path of dll in the zip.
Update the version to 1.4.0.5
=> Update AndroidLogger v1.4.0.5 to the plugin list

src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.5.0/NEWS.textile
=> HTMLTag v1.5.0

src/pl.arm64.json
Collateral benefit of the C++ rewrite, still untested on actual hardware ;)
=> HTMLTag v1.5.0 for Windows on ARM64

src/pl.x64.json
Hi Team, I would like to update the "NX ASCII Database Helper" plugin for version 2.0.0. 
On the basis of version 1.0.0, code highlighting and indentation functions have been added. Improved the plugin running process, implementing automatic formatting when opening files ending in ".dat" and when reloading it.
=> Updata: update "NX ASCII Database Helper" plugin for version 2.0.0

src/pl.x64.json, src/pl.x86.json
=> Update GitSCM to 1.4.10.1

src/pl.x64.json, src/pl.x86.json
See [the release notes](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2) for changes since v8.1.
=> up JsonTools to v8.2

src/pl.x64.json, src/pl.x86.json
https://github.com/rdipardo/npp_preview/blob/v1.3.3.2/ReleaseNotes.txt
=> Preview HTML v1.3.3.2

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **New Variables**: Two new variables have been added for "Use Variables" option:
- **FNAME**: Represents the filename or window title for new, unsaved files.
- **FPATH**: Represents the full path including the filename, or is empty for new, unsaved files.
- **Smaller Fixes**
=> updated MultiReplace to 4.1.1.21

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
https://bitbucket.org/rdipardo/htmltag/src/v1.5.2/NEWS.textile
=> HTMLTag v1.5.2

src/pl.x64.json, src/pl.x86.json
https://github.com/rdipardo/nppFSIPlugin/blob/v0.2.3.1/Changelog.txt
=> F# Interactive v0.2.3.1

src/pl.x64.json
A new common cmd panel added to run last used commands.
With this feature, we can easily run most cmds within NPP.
=> A new cmd panel added to run last used Android and other commands

src/pl.x64.json, src/pl.x86.json
Release v2.0.9.0
- #81: Characters are not displaying correctly
=> - Update CSScriptNpp v2.0.9.0

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
**Implemented updates:**  
- **Fixed CSV Highlighting Reset**: Column highlights are now cleared without affecting syntax colors when switching documents.
=> updated MultiReplace 4.2.2.24

src/pl.x64.json, src/pl.x86.json
Updating npp-java-plugin to 0.4.1
=> Updating npp-java-plugin to 0.4.1

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Performance optimization for CSV Highlighting Reset fix**.
=> updated  MultiReplace 4.2.2.25

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.6.8
=> CSV Lint plug-in update v0.4.6.8

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
=> Release JSTool 1.2503.0

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
Adds definitions for new "Linter++" plugin
=> Add linter++ plugin definitions

src/pl.x64.json, src/pl.x86.json
Add support for search action to the Common Commands Panel, you can quickly search keywords in the list, not need to open the find dialog again.
=> Added support for search action in commands panel

src/pl.x64.json, src/pl.x86.json
fix https://github.com/notepad-plus-plus/nppPluginList/issues/894
=> update bookmark dook to v4.1.2

src/pl.x64.json, src/pl.x86.json
See [release notes](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.4) for a summary of the changes.
=> up JsonTools to v8.4

src/pl.x64.json, src/pl.x86.json
https://github.com/rdipardo/nppFSIPlugin/blob/v0.2.3.2/Changelog.txt
=> F# Interactive v0.2.3.2

src/pl.x64.json
1. Create new buttons in the navigation bar for easier "Data Formatting" and "Show Class"
2. Implemented right-click deletion of a certain row of data and deletion of the entire Class's data
=> Updata: update "NX ASCII Database Helper" plugin for version 3.0.0

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Replace matches**: Allows targeted replacements using match indexes like `1`, `1,3` or `2-5`.
- **List Statistics**: Displays counts for active, total, current, and selected entries below the list.  
*(Disabled by default – enable via `ListStatistics=1` in the INI file.)*
- **Use Variables Performance**: Significantly faster execution of replacements using the "Use Variables" option.
- **Docs and Language**: Minor documentation and wording refinements.
=> updated MultiReplace 4.3.0.26

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Fixed Replace:** Single Replace no longer deletes the match when the replacement text is set.
=> updated MultiReplace 4.3.1.27

src/pl.x64.json, src/pl.x86.json
NppMarkdownPanel Version 0.9.0
=> NppMarkdownPanel Version 0.9.0

src/pl.x64.json, src/pl.x86.json
CSV Lint plug-in update v0.4.7
=> CSV Lint plug-in update v0.4.7

src/pl.x64.json, src/pl.x86.json
https://github.com/rdipardo/npp_preview/blob/v1.3.3.3/ReleaseNotes.txt
=> Preview HTML v1.3.3.3

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Find All**: Extended with three modes – *Find All*, *Find All in All opened Documents*, and *Find All in Files*. Results are shown in a dedicated result window.
- **GroupResults**: New option related to *Find All*. Results can be displayed either mixed in the result window (default) or grouped by list entries.
- **lcmd**: New command `lcmd` added in *Use Variables*. It allows extending the function list with custom helper functions that can be reused for complex replacement tasks.
- **ReplaceAllFromCursor**: New *ReplaceAllFromCursor* in ini file setting that controls where the *Replace All* action begins. The operation can start from the beginning of the document (default) or from the current cursor position.
- **Multilingual Support**: Introduced support for …
=> updated MultiReplace 4.5.0.30

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
Adding new plugin to Plugin Admin
- Tested changes described https://npp-user-manual.org/docs/plugins/#plugin-list and working as expected
=> Add npp-rascript v0.4.1

src/pl.arm64.json, src/pl.x64.json, src/pl.x86.json
- **Extended Mode Fix:** Corrected handling of Extended mode in “Find All” and related operations.
=> updated MultiReplace 4.5.2.32
