- src/pl.x64.json
- src/pl.x86.json
This plugin used to be in the repository (migrated from the old plugin manager), but it was an old version that I hadn't maintained for years and didn't even have a version correctly set.
A few months back I started working on it again (mostly just polishing up the code), and this time I have properly set the version. This is my new release.
> Add Python Indent plugin to x86 and x64

- src/pl.x64.json
- src/pl.x86.json
The EditorConfig plugin v0.4.0 has been released.
This PR updates the x86 entry and adds a x64 entry.
> Release of v0.4.0 of NppEditorConfig

- src/pl.x64.json
- src/pl.x86.json
NppMarkdownPanel is a lightweight plugin for Notepad++ to preview markdown files with a good default style (github style)
> + added new plugin NppMarkdownPanel

- src/pl.x64.json
- src/pl.x86.json
This plugin was previously removed because it did not contain version information. The plugin is unmaintained by it's original author, so I have forked it and added version information, as well as adding 64-bit support.
> Add VisualStudioLineCopy to plugins.

- src/pl.x64.json
- src/pl.x86.json
The plugin has been tested by me and [several other people](https://notepad-plus-plus.org/community/topic/17303/preview-plugin/39), and subsequently announced [here](https://notepad-plus-plus.org/community/topic/17320/preview-html-version-1-3-2-0-both-32-bits-and-64-bits).
> Add PreviewHTML, version 1.3.2.0, both 32 and 64 bits.

- src/pl.x64.json
- src/pl.x86.json
Even the query string separators need to be URI-encoded for some reason, otherwise the updater doesn't download the file.
>  Updated URLs for PreviewHTML plugin, and tested them.

- src/pl.x64.json
- src/pl.x86.json
release-date: 2019-12-16 fixed to 2018-12-16
> fix release date for code alignment plugin. It don't come from the future

- src/pl.x64.json
- src/pl.x86.json
Previous release of my linefilter had an issue with NPP x64 on Windows 10. I found a more recent .NET template and reworked everything. Now it successfully loads, so I need to update the SHA2 hash.
> Updated SHA2 for new version which contains a fix for Windows 10 NPP x64

- src/pl.x64.json
- src/pl.x86.json
Updated GedcomLexer 0.4.0-r140:
- Support for x86 and x64
- Fixed extremely slow loading of GEDCOM files since Notepad++ version 7.7, when the Scintilla component was upgraded from version 3.56 to version 4.14. This upgrade prompted a rewrite of GedcomLexer's core lexer utilizing functions from Scintilla's StyleContext class.
- Since plugin manager does not install the external lexer configuration file with the plugin, GedcomLexer now detects a missing configuration file, and displays a message box with instructions to repair the situation.
> Update GedcomLexer for x86 and new GedcomLexer for x64

- src/pl.x86.json
Fix many errors.
Convert links to https when possible.
Remove link to possible malware site.
Fix broken links.
Add missing homepages.
Fix erroneous homepages.
Fix syntax errors
Add missing author credits.
Simplify descriptions and improve consistency.
> Greatly improve plugin list, including security-related enhancements

- src/pl.x64.json
- src/pl.x86.json
Files have been re-uploaded to fix whitespace replacement. This was due to github "upload files" function which obviously replace tabs
> XMLTools 3.0.0.3

- README.md
Link from NPP page refers to front page.
Hence readers would need to see the lists linked at front page.
> Adding links to list files

- src/pl.x64.json
- src/pl.x86.json
Add RegexTrainer plugin for both x64 and x86.  This RegexTrainer plugin is created using c# net framework 4 and supports for a complex expression.
> RegexTrainer

- src/pl.x64.json
- src/pl.x86.json
v2.0.1 is the same as v2.0.0 but for plugins API of Notepad++ 7.7 and above
and will hopefully eliminate the confusion the users have when updating Notepad++
from older versions and when addressing Compare2 variants.
> Update Compare2 plugin to v2.0.1

- validator.py
Check arguments that are passed to validator.py.
If there are no arguments, stop the script in order to avoid deleting all the files in the current directory.
This fixes issue #261
> Check arguments to validator

- src/pl.x64.json
- src/pl.x86.json
RestApiToText v1.2:
1. Added JSON pretty-printing for responses with a Content-Type response header containing "application/json".
2. Added support for the HEAD and OPTIONS verbs.
3. URLs with no verb now default to a GET.
> RestApiToText v1.2

- src/pl.x64.json
- src/pl.x86.json
Version 1.3.0.0:
1. Added new __**RestApiToTextOptions**__ section to allow users to control the behavior of RestApiToText.
2. Added RestApiToText option called __ShowResponseHeaders__ to display response headers in addition to the response itself.
3. URL querystrings are now encoded before they are sent.
4. Added the ability to pass a body with the __DELETE__ verb.
5. Fixed issue where the __PATCH__ verb was not passing the body.
> Version 1.3.0.0

- src/pl.x64.json
- src/pl.x86.json
Release output are generated with GitHub action: https://github.com/blu3mania/npp-papyrus/blob/main/.github/workflows/release.yml
VirusTotal scan results linked on release page: https://github.com/blu3mania/npp-papyrus/releases
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/686714943
> Update Papyrus Script Lexer plugin to v0.1.1.13 for both 64bit and 32bit

- src/pl.x64.json
- src/pl.x86.json
* FWDataViz 1.0.3.0 release adds [Record Type Themes](https://github.com/shriprem/FWDataViz/blob/master/docs/file_type_extract_dialog.md) feature
* GotoLineCol 1.2.0.1 minor update to fix the balloon tip text for the toolbar icon
> FWDataViz v1.0.3.0 & GotoLineCol 1.2.0.1 updates (x86 & x64)

- src/pl.x64.json
- src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/760094277
> Update Papyrus Script Lexer plugin to v0.2.1.18 for both x64 and x86

- src/pl.x64.json
AutoSave: avoid rolling tabs when saving all files with overwrite settings (requested)
LanguageHelp: fix bug freezing NPP when main menu is hidden, added $firstline$ expansion keyword
MenuIcon: fix bug freezing NPP when main menu is hidden, added $firstline$ expansion keyword, fixed default folder containing the icons
OpenSelection: fix bug freezing NPP when main menu is hidden, added $firstline$ expansion keyword 
RunMe: fix bug freezing NPP when main menu is hidden, added $firstline$ expansion keyword
TakeNotes: added $firstline$ expansion keyword (requested)
> Fix bug freezing NPP when main menu is hidden

- src/pl.x64.json
Fix a NPP crash due to a buffer overrun
> Upgrade TakeNotes plugin to v1.22

- src/pl.x86.json
These backslashes should be a single forward slash, thus preventing the accidental escaping of a character.
> Fix an erroneous backslashes

- src/pl.arm64.json
- src/pl.x64.json
- src/pl.x86.json
[ _Resubmitting fresh PR since the Appveyor build failed on the previous PR due to extraneous factors._ ]
1. [FWDataViz 2.0.0.0 Release](https://github.com/shriprem/FWDataViz/releases/tag/v2.0.0.0) with [darkmode-enabled plugin UI](https://github.com/shriprem/FWDataViz/blob/master/docs/dark_mode_ui.md)
2. [GotoLineCol 2.0.0.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.0.0.0) with [darkmode-enabled plugin UI](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/blob/master/DarkModeUI.md)
> FWDataViz & GotoLineCol with Darkmode-enabled plugin UI

- src/pl.x64.json
- src/pl.x86.json
I just released version 0.9.5 of my NppMenuSearch plugin. fixes several bugs and implements some new features:
* NEW: corresponding menu icon or toolbar icon is displayed next to a result entry
* NEW: remember results window size after restart ([issue #23](https://github.com/peter-frentrup/NppMenuSearch/issues/23))
* NEW: support newer preference dialog pages
* FIX: better support for high resolution displays ([issue #24](https://github.com/peter-frentrup/NppMenuSearch/issues/24))
* FIX: display real shortcut instead of hard-coding CTRL+M in the help texts ([issue #22](https://github.com/peter-frentrup/NppMenuSearch/issues/22))
* FIX: work around duplicate dialog controls with same id ([issue #28](https://github.com/peter-frentrup/NppMenuSearch/issues/28))
* FIX: support hidden toolbar …
> Update NppMenuSearch to 0.9.6

- src/pl.x64.json
- src/pl.x86.json
Random Values plug-in update v0.2.1.
I appreciate that Notepad++ was updated just today to 8.1.9.1 to include some plug-in updates, including my CSV Lint plug-in update from yesterday, that last update v0.4.3 had some important bugfixes.
This Random Values plugin update is not as urgent, as it mainly adds the new fluent UI icons and some minor bugfixes, so as far as i am concerned there's no need to update Notepad++ immediately again, this one can wait for some update down the line somewhere. Cheers, Bas
> Random Values plug-in update v0.2.1

- src/pl.x64.json
- src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/2085580925
Note that VirusTotal has a less than 10% report rate of "Lazy" trojan on [PapyrusPlugin-v0.4.0-x86.zip](https://www.virustotal.com/gui/file-analysis/ZmU2M2NlZDM3ZWRiNzAxMWM0ZGYxYTAyZjFkZmFiZjQ6MTY0ODk5Njk1Ng==/detection), which is a false alarm. Originally there were 8 reports so I moved a method around, which got the number of reports down to 4 but didn't get rid of it. Since it's an obvious false alarm because the same builder is used for both x86 and x64 builds, and there has been no report on [PapyrusPlugin-v0.4.0-x64.zip](https://www.virustotal.com/gui/file-analysis/ZDA5YTkzOTM5YTQ3ZDZjYTc4OTZmZjhhMGU3ZDY5YWM6 …
> Update Papyrus Script Lexer plugin to v0.4.0.27 for both x64 and x86, to be compatible with the upcoming Notepad++ release after 8.3.3

- src/pl.x64.json
- src/pl.x86.json
The new Scintilla 5+ updates change  SCI_GETCURLINE count to not return the `\0` meaning the storage buffer must be +1.  This update fixes that.
> ColumnTools update for Scintilla 5+

- src/pl.x64.json
- src/pl.x86.json
The new version adapts to the new functionality of menu shortcuts coming between "?" menu item and the "x". The plugin is backward compatible.
> update jN v2.2.185.8

- src/pl.x64.json
- src/pl.x86.json
* Added: menu icons for "Run with arguments" and "Run as administrator"
* Added: Toolbar entries for "Run with arguments" and "Run as administrator"
* Added: Tab context menu entries for "Run with arguments" and "Run as administrator"
* Added: Run me with a custom *verb*
* Fix: Cancelling a "Run me w/ arguments" would not stop the run
* Fix: Remove the tab flickering for save all unamed buffers before running
> RunMe v1.60

- src/pl.x64.json
Hi,
I'm using this plug-in every day since several years and I'm sure other users will find it useful too. I've tested the installation via plugin admin as described.
Further information about the plug-in: https://bitbucket.org/uph0/filefinder/src/master/readme.txt
Thank you!
PS: Maybe adding a note about a N++ installation version which actually works with the debug builds (7.8.1) would be helpful too, since placing the debug builds into a current installation (8.4.7) didn't work.
> Request to add "FileFinder" to the plug-ins list

- src/pl.x64.json
- src/pl.x86.json
Latest CodeQL scan: https://github.com/blu3mania/npp-papyrus/actions/runs/3575174400
> Update Papyrus Script Lexer plugin to v0.5.1.30 for both x64 and x86

- src/pl.x64.json
- src/pl.x86.json
Update Elastic Tabstops to version 1.5.0 for x86 and x64 code.
> Update Elastic Tabstops to version 1.5.0

- src/pl.x64.json
- src/pl.x86.json
File Finder v0.3
- Bugfix: 'Auto validate file names' doesn't remove non-existing files from internal file list
>  Update to File Finder v0.3

- src/pl.x64.json
- src/pl.x86.json
1. [Random JSON generation](/docs/README.md#generating-random-json-from-a-schema) from a non-schema file.
2. Tests for random JSON generation.
1. Bug with random JSON generation where *all keys* (including *non-required keys*) in an object schema would always be included in random JSON. Now each object will have a random set of keys that is a superset of the required keys and a subset of all validated keys.
1. [JSON Schema generation](/docs/README.md#generating-json-schema-from-json) is back!
1. Support for extended ASCII characters (i.e., anything from `0x7f` (⌂) to `0xff` (ÿ)) in random JSON.
1. Non-ASCII characters (e.g., 😀, Я) are now displayed normally rather than being converted to ASCII using the `\u` notation (e.g., `\ud83d\ude00`, `\u042f`). Resolve [Issue …
> Update JsonTools to 4.8.1; JSON schema stuff

- src/pl.x64.json
- src/pl.x86.json
1. Auto-inference of newlines
2. JSON chunking
3. Find/replace form with ability to edit file
4. Write chunks to separate files
1. Now works with multiple view, multiple instances
2. patternProperties validation in JSON schema
3. Leading + signs in numbers
4. Massive performance improvement for tree viewer in files with many thousands of children of the top-level iterable.
5. Numerous bugfixes
> bump HugeFiles to 0.4, JsonTools to 4.10.0

- src/pl.x86.json
Support and switch to the fresh new OpenAI ChatGPT API model (from Davinci) for better AI results and lower (token) cost.
> NppOpenAI API update for ChatGPT support

- src/pl.x64.json
- src/pl.x86.json
Address [JsonTools issue 30](https://github.com/molsonkiko/JsonToolsNppPlugin/issues/30)
Release link [here](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v4.11.1)
> up JsonTools to 4.11.1, fix crash bug in 4.11.0

- validator.py
Improve Markdown table syntax compatibility of [`doc/plugin_list*.md` files](https://github.com/notepad-plus-plus/nppPluginList/tree/master/doc) by editing the `validator.py` Markdown generation:
- Place empty lines between the heading, paragraph (mentioning the version), and the table. Without the empty line before the table, some Markdown implementations might not detect the table.
- Additional change for the table header row: add one space between "*Plugin name*" and the `|` character before it.
See issue notepad-plus-plus/nppPluginList#603 for more information.
The automatically queued AppVeyor build has finished and the artifacts are available. The Markdown files in the artifacts show that these changes work as I intended.
Testing before the AppVeyor build: I tried the `*` operator …
> validator.py: Output empty lines in plugin list Markdown generation (issue #603)

- src/pl.x64.json
- src/pl.x86.json
The [original plugin host](https://github.com/ppv/NPPFSIPlugin) appears to be dormant.
Meanwhile, [my fork](https://github.com/rdipardo/nppFSIPlugin#readme) has added 64-bit compatibility, integration with Lexilla's [F# lexer], a dark mode theme, and better default settings for current versions of the .NET SDK.
The code base was ported to Free Pascal so releases can be [built in CI] with a free and open source toolchain. There may even be an ARM build someday, when/if the Free Pascal compiler makes Windows on ARM64 an [officially supported target].
Old and new plugin code is under the original MIT license; library units are licensed under the (L)GPL v3 or MPL v2, depending on which project they were extracted from.
I haven't formally asked @ppv about taking over. I could change the name, …
> Update F# Interactive to 0.2.1.1

- src/pl.x64.json
- src/pl.x86.json
1. HUGE tree view performance improvement
2. Automatic error checking after user edits file
3. Many more JSON schema keywords supported
4. UI improvements
- removed annoying dinging in tree view
- some UI elements are bigger
5. Python-style `#` comments now can be ignored when parsing
6. Better performance in general
> update JsonTools to 4.14.0

- src/pl.x64.json
- src/pl.x86.json
CSV Lint plug-in update v0.4.6.4, patched a small (but annoying) bug in the new split on Nth occurrence feature, the plugin version does't change, this is only so this bugfix will also be distributed in next Notepad++ version
> CSV Lint plug-in update v0.4.6.4 (patch)

- src/pl.x64.json
- src/pl.x86.json
* Parser is faster and can handle more deviations from the JSON standard, including unquoted keys, hex numbers, and the `undefined`, `True`, `False`, and `None` literals
* User does not need to enable special options to allow parsing of error-ridden documents
* RemesPath has better error handling and messages
* Miscellaneous bugfixes
* JSON Schema validation now supports `minLength` and `maxLength` properties for strings.
> Update JsonTools to v5.0.0

- src/pl.x64.json
- src/pl.x86.json
MenuIcons v2.03 (2023-05-26)
- Fix a problem with menu items containing some special characters: < > " '
TakeNotes v1.26 (2023-05-26)
- Fix a problem with the note extension not being added to the note name when a "." was already present.
> MenuIcons v2.03 and TakeNotes v1.26

- src/pl.x64.json
- src/pl.x86.json
1. Added support for tab indentation. Fix [issue #38](https://github.com/molsonkiko/JsonToolsNppPlugin/issues/38).
2. Hitting `Enter` while in the error form causes the form to refresh.
3. In the error form, searching for the next row starting with a character now wraps around.
4. Python constants `nan` and `inf` can now be parsed as `NaN` and `Infinity` respectively.
5. Support for numbers with leading decimal points and hex numbers in RemesPath.
6. Unquoted strings in RemesPath can now contain leading `$`, Unicode escapes, and all the Unicode characters that are allowed in unquoted JSON5 keys.
7. Add caching of RemesPath queries for slightly better performance on repeated execution of the same query.
8. Massively impreoved test coverage.
1. All arithmetic operations (`+`, `-`, `*`, `/`, …
> Bump JsonTools to v5.4.0

- src/pl.arm64.json
- Extended 'Find/Replace' fix to list operations, preventing matches being skipped.
- Fixed sed command generation in 'Export to Bash' function, replaced slashes with delimiters.
> MultiReplace Bug Fix Release 1.0.3.4

- src/pl.x86.json
- Extended 'Find/Replace' fix to list operations, preventing matches being skipped.
- Fixed sed command generation in 'Export to Bash' function, replaced slashes with delimiters.
> MultiReplace Bug Fix 1.0.3.4

- src/pl.x64.json
- src/pl.x86.json
Major changes to [JsonTools](https://github.com/molsonkiko/JsonToolsNppPlugin):
1. Parse multiple selections of JSON
2. Add ability to dump selected JSON strings as raw text, dump raw text as JSON strings
3. Allow preserving of comments when pretty-printing/compressing JSON
4. Many improvements to RemesPath
> up JsonTools to v5.6

- src/pl.x64.json
- src/pl.x86.json
Columns++ 1.0.2 fixes a serious bug in 1.0.1 that can lead to a hang (necessitating a force close of Notepad++ and consequent loss of unsaved data in all open tabs).
> Update Columns++ to 1.0.2

- src/pl.x64.json
- src/pl.x86.json
[See the changelog for all changes](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/CHANGELOG.md#710---2024-02-28)
* Add support for multiple JSON schema validation problems; validation problems are shown in the error form
* fix numerous bugs related to automatic validation and linting after editing
* major improvement to selection-based mode (earlier versions of JsonTools will have major issues with selection-based mode for Notepad++ 8.6.5 onward; this version still has problems for Notepad++ 8.6.3 and 8.6.4)
* Fix issue (in Notepad++ 8.6 onwards) where Ctrl+C and Ctrl+X could sometimes stop working in textboxes of JsonTools forms.
> update JsonTools to v7.1

- src/pl.x64.json
- src/pl.x86.json
- Fixed a crash bug documented in [JsonTools issue 60](https://github.com/molsonkiko/JsonToolsNppPlugin/issues/60#issuecomment-2065419075).
- Fixed some other minor bugs and sources of irritation
- Added command to check JSON syntax (without opening tree view or reformatting document)
1. [`Check JSON syntax now` command](/docs/README.md#check-json-syntax-now).
1. Made it so that reloading the [error form](/docs/README.md#error-form-and-status-bar) by pressing `Enter` would not cause certain message boxes to appear, to eliminate a potential "infinite" loop where the user would hit `Enter` to close the message box, and that moved focus back to the error form, which then repeated the cycle when they lifted the `Enter` key.
2. [Automatic …
> Up JsonTools to v7.2

- src/pl.x64.json
- src/pl.x86.json
- validator.py
*Preview HTML*'s download host can't parse escaped URLs (<https://github.com/notepad-plus-plus/nppPluginList/commit/6a764d574e6220581cc20537dbdd2ed1a0392927#commitcomment-144093569>), even though it had no problem until just recently ¯&#x005C;_(ツ)_/¯
__*Un*__-escape download URLs in the Python script
> Restore Preview HTML

- src/pl.arm64.json
- src/pl.x64.json
- src/pl.x86.json
- **Fixed Regex Capture Groups in 'Use Variables' Mode:** Resolved an issue where nil values in capture groups caused all subsequent groups to reset to nil, even when they had matching values.
> updated MultiReplace to v3.1.2.18

- src/pl.x64.json
1. Fix some stable issues, if no file selected, click to read will crash.
2. An APK manager added to the file explorer.
3. Even if no year and month also can be converted to corresponding date.
4. Refactor some codes to better performance.
> Update AndroidLogger to fix stable issues and impl an apk manager in the file explorer

- src/pl.arm64.json
- src/pl.x64.json
- src/pl.x86.json
- **Header Column Menu**: Right-click on the header to toggle columns like `Find count`, `Replace count`, `Comments`, and `Delete`.
- **Comments Column**: Add custom comments to entries via the new `Comments` column.
- **Column Locking**: Lock the width of columns (`Find`, `Replace`, `Comments`) with a double-click on the header divider. A lock icon shows the status.
- **Configuration Options**: Manage settings via the INI file located at  
`C:\Users\<Username>\AppData\Roaming\Notepad++\plugins\Config\MultiReplace.ini`:
- **DoubleClickEdits**: To disable direct editing on double-click, set `DoubleClickEdits=0` (default: enabled).
- **Tooltips**: To disable tooltips, set `Tooltips=0` (default: enabled).
- **AlertNotFound**: To disable notifications for unsuccessful searches, set …
> updated MultiReplace to v4.1.0.20

- src/pl.x64.json
- src/pl.x86.json
The pycalc plugin enables the execution of python code directly within the editor upon pressing the Enter key.
https://github.com/pycalc-plugin/notepad-plus-plus
> Add plugin: pycalc

- src/pl.x64.json
- src/pl.x86.json
See changes from [v8.3](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.3) and [v8.3.1](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.3.1).
v8.3.1 was released so soon after v8.3 because I discovered a very easily replicated bug in v8.3 (which had actually been present since [v6.1](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/CHANGELOG.md#610---2023-12-28) and I just hadn't dealt with it) that could cause NPP to crash, and I did not want the plugin list to have a version of JsonTools that I knew could so easily cause a crash.
> Up JsonTools to v8.3.1

- src/pl.x64.json
- src/pl.x86.json
Replace "searchfolder" with search /f, also provides /o:opened, /r: recursive, /m: mark all, /i: ignorecase, /x:mode. The mode has the same mean with NPP search flags.
> Fix non-ASCII folder search issue and provides search options

- src/pl.x64.json
- src/pl.x86.json
Added [cmdout] feature with ansi charset support, and update toolbar  icons to align with Fluent UI design standards.
```
<oscmd>
<desc>Python Run</desc>
<cmd>python</cmd>
<param>@!</param>
<type>cmdout</type>
<charset>ansi</charset>
</oscmd>
```
> Added [cmdout] feature and update icons to align Fluent UI

- src/pl.arm64.json
- src/pl.x64.json
- src/pl.x86.json
- **AllFromCursor Option:** New setting to control the start position of “Find All”, “Replace All”, and “Mark”. When enabled (AllFromCursor=1), these actions begin at the current cursor position instead of the document start. With **Wrap Around** enabled, they always cover the entire file.
> updated MultiReplace 4.5.1.31

- src/pl.x64.json
Added Redis plugin.
Version: 1.0.0
Notepad++ plugin to view Redis keys and values
Download: [Notepad++RedisPlugin_v1.0.0.zip](https://github.com/bakingam1983/Notepad.plus.plus-RedisPlugin/releases/download/v1.0.0/Notepad++RedisPlugin_v1.0.0.zip)
> Added RedisPlugin
